# Generated by Django 4.1.13 on 2024-02-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coin_id", models.CharField(max_length=100)),
                ("alert_name", models.CharField(max_length=100)),
                ("alert_price", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "created"), ("disabled", "disabled")],
                        default="created",
                        max_length=100,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("createdBy", models.IntegerField(max_length=100)),
            ],
        ),
    ]
